# Generated by Django 3.0.3 on 2021-01-09 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('desc', models.TextField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('food', 'FOOD'), ('drinks', 'DRINKS'), ('travel', 'TRAVEL'), ('shopping', 'SHOPPING'), ('e-commerce', 'E-COMMERCE'), ('grocery', 'GROCERY'), ('veggies', 'VEGETABLES'), ('fruits', 'FRUITS'), ('miscellaneous', 'MISCELLANEOUS')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
