# Generated by Django 3.0.3 on 2021-01-10 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('desc', models.TextField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('clothes', 'CLOTHES'), ('mobile', 'MOBILE'), ('laptop', 'LAPTOP'), ('home appliances', 'HOME_APPLIANCES'), ('miscellaneous', 'MISCELLANEOUS')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
